version: '3'
services:
  bertscore:
    image: bigabig/bertscore:latest
    ports:
      - "4444:4444"
    volumes:
      - ./bertscore_models:/models
  entailment:
    image: bigabig/entailment:latest
    ports:
      - "5555:4444"
    volumes:
      - ./entailment_models:/models
  qgqa:
    image: bigabig/qgqa:latest
    ports:
      - "6666:4444"
    volumes:
      - ./qgqa_models:/models
  factcc:
    image: bigabig/factcc:latest
    ports:
      - "7777:4444"
    volumes:
      - ./factcc_models:/models
      - ./factcc_checkpoint:/checkpoint
